name: Build and Deploy

on:
  push:
    branches:
      - main 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' 

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: List dist directory
        run: ls -la dist

      - name: Checkout build-repo
        uses: actions/checkout@v3
        with:
          repository: usuario/build-repo
          token: ${{ secrets.BUILD_REPO_TOKEN }}
          path: build-repo
          ref: main 

      - name: Copy build files
        run: |
          cp -r dist/* build-repo/

      - name: Commit and push build files
        run: |
          cd build-repo
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Deploy build files"
          git push origin main  # Ou a branch correta do repositório de build
        env:
          GIT_TOKEN: ${{ secrets.BUILD_REPO_TOKEN }}